// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnKHVb4WMIbyxJfBhV3kkoPIeM8OOGxi4',
    appId: '1:849575801019:web:b72e0f599d2bf6dd4db99e',
    messagingSenderId: '849575801019',
    projectId: 'ybarber-b4146',
    authDomain: 'ybarber-b4146.firebaseapp.com',
    storageBucket: 'ybarber-b4146.appspot.com',
    measurementId: 'G-S4VPYE9DZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6EbA8NGCrz-GBrcVuuzjaCPs5lXmj47E',
    appId: '1:849575801019:android:f9f9e36b2b46086e4db99e',
    messagingSenderId: '849575801019',
    projectId: 'ybarber-b4146',
    storageBucket: 'ybarber-b4146.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-nse06IGLj9De0oHPThmRf6KiHgwDUmc',
    appId: '1:849575801019:ios:c079224693c7733d4db99e',
    messagingSenderId: '849575801019',
    projectId: 'ybarber-b4146',
    storageBucket: 'ybarber-b4146.appspot.com',
    iosBundleId: 'com.example.ybarber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-nse06IGLj9De0oHPThmRf6KiHgwDUmc',
    appId: '1:849575801019:ios:c079224693c7733d4db99e',
    messagingSenderId: '849575801019',
    projectId: 'ybarber-b4146',
    storageBucket: 'ybarber-b4146.appspot.com',
    iosBundleId: 'com.example.ybarber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnKHVb4WMIbyxJfBhV3kkoPIeM8OOGxi4',
    appId: '1:849575801019:web:7cc9558be1c7888c4db99e',
    messagingSenderId: '849575801019',
    projectId: 'ybarber-b4146',
    authDomain: 'ybarber-b4146.firebaseapp.com',
    storageBucket: 'ybarber-b4146.appspot.com',
    measurementId: 'G-57RBYZFJJE',
  );
}
